
version=0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name="sam-app"
capabilities="CAPABILITY_IAM"
region="eu-west-2"
s3_bucket = "sam-cli-upload-bucket-sam-app"
s3_prefix = "test"
confirm_changeset = true