AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  

Globals:
  Function:
    Timeout: 3
    CodeUri: src/
    Runtime: nodejs14.x

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: src/hello.handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
